version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
  path-filtering: circleci/path-filtering@0.1.2
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.15.0'
      - run: node --version
      - run: yarn
      - aws-cli/setup:
          configure-default-region: true 
          configure-profile-region: true 
          disable-aws-pager: true 
          override-installed: false 
          aws-access-key-id: AKIAXUF4TWET7HZ4JF57 
          aws-secret-access-key: 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 
          aws-region: us-west-1
      - eb/setup
      - run:
            name: "build job"
            command: |
              echo "this is the build job"
      - run:
            name: Back-End Install
            command: |
              yarn api:install
      - run:
            name: Back-End Build
            command: |
              yarn api:build
      - run:
            name: Back-End Deploy
            command: |
              yarn api:deploy
      - run:
            name: Front-End Install
            command: |
              yarn frontend:install
      - run:
            name: Front-End Build
            command: |
             yarn frontend:build
      - run:
            name: Front-End Deploy
            command: |
              yarn frontend:deploy
      - run:
            name: success confirmation
            command: |
              echo "build and deployment successful"
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
             only: main
      - test